FROM mysql

COPY ./db/products.sql /docker-entrypoint-initdb.d/products.sql

ARG MYSQL_ROOT_PASSWORD
ARG MY_SQL_USER
ARG MY_SQL_PASSWORD


ENV MYSQL_ROOT_PASSWORD $MYSQL_ROOT_PASSWORD
ENV MY_SQL_USER $MY_SQL_USER
ENV MY_SQL_PASSWORD $MY_SQL_PASSWORD
