version: '3'

services:
  api:
    container_name: nginx-service
    image: nginx:latest
    volumes: 
      - ./php-task:/var/www/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:5000
    depends_on:
      - php-fpm
    networks:
      - shop

  php-fpm:
    container_name: php-fpm-service
    image: php:fpm
    volumes: 
      - ./php-task:/var/www/html/
    command: bash -c "docker-php-ext-install pdo_mysql && php-fpm"
    environment:
      - SERVER=${SERVER}
      - DATABASE=${DATABASE}
      - USERNAME=root
      - PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 9000:9000
    networks:
      - shop
    
  ui:
    container_name: frontend-service
    build:
      context: ./front/
      target: runner
      args:
        - API_URL=${API_URL}
    ports:
        - 3000:3000
    depends_on:
      - php-fpm
      - api
      - db
    networks:
      - shop

  db:
    container_name: db-service
    image: mysql:latest
    restart: always
    volumes:
      - ./db/database:/var/lib/mysql
      - ./db/products.sql:/docker-entrypoint-initdb.d/products.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - shop

networks:
  shop:
