version: '3.1'

services:
  api:
    container_name: nginx-service
    image: php:fpm
    volumes: 
      - ./php-task:/var/www/html/
      - ./etc/nginx.conf:/var/nginx/conf.d/default.conf
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm-service
    image: php:fpm
    volumes: 
      - ./php-task:/var/www/html/
    command: bash -c "docker-php-ext-install pdo_mysql && php-fpm"
    environment:
      SERVER: ${SERVER}
      DATABASE: ${DATABASE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
      - 9000:9000
    networks:
      - app-network
    
  ui:
    build:
      context: ./front/
      args:
        API_URL: ${API_URL}
    command: npm start
    networks:
      - app-network
    ports:
        - 3000:3000
    depends_on:
      - php-fpm
      - api
      - db

  db:
    container_name: db-service
    image: mysql
    restart: always
    volumes: 
      - ./db/products.sql:/docker-entrypoint-initdb.d/products.sql
    environment:
      MY_SQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD}
      MY_SQL_USER: ${MY_SQL_USER}
      MY_SQL_PASSWORD: ${MY_SQL_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
